version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: akaunting_app
    ports:
      - "8090:80" # Expose port 80 of the container on port 8080 of the host
    volumes:
      - .:/var/www/html
    environment:
      APP_ENV: production
      APP_DEBUG: "true"
      APP_URL: http://localhost:8090
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: akaunting_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: akaunting
      MYSQL_USER: akaunting_user
      MYSQL_PASSWORD: akaunting_pass
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
